import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import path from 'path';

// Load env vars
dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const OLD_URL = 'https://imfhacvrivasciftaujm.supabase.co';
// The old service key recovered from the previous .env state
const OLD_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZmhhY3ZyaXZhc2NpZnRhdWptIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTE1NzQyNSwiZXhwIjoyMDg0NzMzNDI1fQ.0IzRioNPcH-pcsWPQo3LrdAIGkVbC3ONgjAiFDdh4mM';

const NEW_URL = process.env.VITE_SUPABASE_URL!;
const NEW_KEY = process.env.SUPABASE_SERVICE_KEY!;

if (!NEW_URL || !NEW_KEY) {
  console.error('❌ New Supabase URL or Service Key missing in .env');
  process.exit(1);
}

const oldSupabase = createClient(OLD_URL, OLD_KEY);
const newSupabase = createClient(NEW_URL, NEW_KEY);

async function migrateUsers() {
  console.log('🚀 Starting user migration from Old Supabase to New Supabase...');

  // 1. Fetch users from OLD database
  console.log('Fetching users from old database...');
  const { data: oldUsers, error: fetchError } = await oldSupabase
    .from('users')
    .select('*')
    .order('id', { ascending: true });

  if (fetchError || !oldUsers) {
    console.error('❌ Error fetching old users:', fetchError);
    return;
  }

  console.log(`✅ Found ${oldUsers.length} users to migrate.`);

  let successCount = 0;
  let failCount = 0;

  for (const user of oldUsers) {
    console.log(`\nMigrating user [${user.id}] ${user.name}...`);
    
    // Validate email
    let email = user.email;
    if (!email || !email.includes('@')) {
      email = `user${user.id}@myportal.internal`;
      console.log(`  ⚠️  Invalid/missing email, using fallback: ${email}`);
    }

    try {
      // 2. Create Auth User in NEW Supabase
      console.log(`  -> Creating auth user...`);
      // We set a temporary password. Users will need to use their PIN if kiosk, or reset password if web.
      const defaultPassword = `SemRumo${user.id}!2026`; 
      
      const { data: authData, error: authError } = await newSupabase.auth.admin.createUser({
        email: email,
        password: defaultPassword,
        email_confirm: true,
        user_metadata: { name: user.name }
      });

      if (authError) {
        // If user already exists in Auth, we can try to find them, but for a new DB it shouldn't happen
        console.error(`  ❌ Error creating auth user: ${authError.message}`);
        failCount++;
        continue;
      }

      const authId = authData.user.id;
      console.log(`  ✅ Auth user created: ${authId}`);

      // 3. Insert into NEW database (users table)
      // Exclude id from insert if we want to preserve it, but Supabase might block inserting into identity columns unless overridden.
      // BigSerial is generated by default. We can try to insert the ID directly to preserve relations.
      const { error: dbError } = await newSupabase.from('users').insert({
        id: user.id, // Preserving original ID is critical for related tables later
        auth_id: authId,
        name: user.name,
        email: email,
        role: user.role,
        company: user.company,
        department: user.department,
        status: user.status,
        pin: user.pin || '000000',
        requires_new_pin: user.requires_new_pin ?? true,
        nif: user.nif,
        cc: user.cc,
        niss: user.niss,
        nationality: user.nationality,
        marital_status: user.marital_status,
        address: user.address,
        birth_date: user.birth_date,
        admission_date: user.admission_date,
        phone: user.phone,
        mobile_phone: user.mobile_phone,
        whatsapp_enabled: user.whatsapp_enabled,
        emergency_contact: user.emergency_contact,
        work_start_time: user.work_start_time,
        work_end_time: user.work_end_time,
        lunch_start_time: user.lunch_start_time,
        lunch_end_time: user.lunch_end_time,
        vacation_days_yearly: user.vacation_days_yearly,
        vacation_days_carryover: user.vacation_days_carryover,
        vacation_adjustments: user.vacation_adjustments,
        photo_url: user.photo_url,
        bio: user.bio,
        iban: user.iban,
        attendance_config: user.attendance_config,
        onboarding_tasks: user.onboarding_tasks,
        documents: user.documents,
        location_id: user.location_id,
        location_ids: user.location_ids,
        schedule_template_id: user.schedule_template_id,
        schedule_cycle_start_date: user.schedule_cycle_start_date,
        must_change_password: true
      });

      if (dbError) {
        console.error(`  ❌ Error inserting to public.users: ${dbError.message}`);
        failCount++;
      } else {
        console.log(`  ✅ Successfully migrated ${user.name}`);
        successCount++;
      }

    } catch (e: any) {
      console.error(`  ❌ Unexpected error: ${e.message}`);
      failCount++;
    }
  }

  console.log('\n========================================');
  console.log(`🏁 Migration Completed!`);
  console.log(`✅ Success: ${successCount}`);
  console.log(`❌ Failed: ${failCount}`);
  
  if (successCount > 0) {
    console.log(`\n⚠️  IMPORTANT: Please update the sequence so future users don't get ID conflicts:`);
    console.log(`Run this in the new Supabase SQL Editor:`);
    console.log(`SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));`);
  }
}

migrateUsers().catch(console.error);
